accounts/urls.py
from django.urls import path
from .views import (
    user_register,
    user_login,
    user_logout,
)

app_name = "accounts"

urlpatterns = [
    path("register/", user_register, name="register"),
    path("login/", user_login, name="login"),
    path('logout/', user_logout, name='logout'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("task.urls")),
    path("auth/", include("accounts.urls")),
]

task/urls.py
# Django Imports
from django.urls import path

# Own Imports
from task import views


app_name = "task"

urlpatterns = [
    path("", views.home, name="home"),
    path("create/", views.create_todo, name="create_note"),
    path("<int:pk>/", views.view_note, name="view_note"),
    path("<int:pk>/edit/", views.update_note, name="edit_note"),
    path("<int:pk>/delete/", views.delete_note, name="delete_note"),
]

accounts/models.py
from django.db import models

# Create your models here.

task/models.py
# Django Imports
from django.db import models
from django.contrib.auth.models import User


class Todo(models.Model):
    """Database schema for todos table."""

    title = models.CharField(max_length=100)
    description = models.TextField(max_length=600)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    completed = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Todos"
        db_table = "todos"
        ordering = ["-date_created"]

accounts/forms.py
# Django Imports
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm


class UserRegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("username", "password")
        widgets = {
            "username": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Username",
                    "type": "text",
                }
            ),
            "password": forms.PasswordInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Enter password",
                    "type": "password",
                }
            ),
        }


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Input email address",
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Input password"}
        )
    )

task/forms.py
# Django Imports
from django import forms

# Own Imports
from task.models import Todo


class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ("title", "description", "completed")
        widgets = {
            "title": forms.TextInput(
                attrs={
                    "placeholder": "Title of task",
                    "class": "form-control",
                }
            ),
            "description": forms.TextInput(
                attrs={
                    "placeholder": "Description of task",
                    "class": "form-control",
                }
            ),
            "completed": forms.CheckboxInput(
                attrs={
                    "placeholder": "Completed task?",
                    "class": "form-control required checkbox form-control-checkbox",
                }
            ),
        }

accounts/views.py
# Django Imports
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

# Own Imports
from accounts.forms import UserRegisterForm, AuthenticationForm


def user_register(request: HttpRequest) -> HttpResponse:
	form = UserRegisterForm()
	if request.method == "POST":
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			# get fields from form
			username = form.cleaned_data["username"]
			password = form.cleaned_data["password"]

			# create and save user to database
			user: User = User.objects.create_user(
				username=username, password=password
			)
			user.save()
			messages.success(request, "Account created successfully!")
			return redirect("accounts:login")

		messages.error(request, "Account creation failed!")
		return redirect("accounts:register")

	return render(request, "accounts/sign-up.html", {"form": form})


def user_login(request):
	form = AuthenticationForm()

	if request.method == "POST":
		form = AuthenticationForm(None, request.POST)
		if form.is_valid():
			username = request.POST.get("username")
			password = request.POST.get("password")

			user = authenticate(username=username, password=password)
			if user.is_active:
				login(request, user)
				messages.success(
					request, f"Welcome {username}, you are logged in."
				)
				return redirect("task:home")
			messages.error(request, "User login failed!")
			return redirect("accounts:login")

	elif request.method == "GET":
		if request.user.is_authenticated:
			return redirect("task:home")

		form.fields['username'].widget.attrs['class'] = "form-control"
		form.fields['username'].widget.attrs['placeholder'] = "Username"
		form.fields['password'].widget.attrs['class'] = "form-control"
		form.fields['password'].widget.attrs['placeholder'] = "Password"
		return render(request, "accounts/login.html", {"form": form})


@login_required(login_url="/auth/login/")
def user_logout(request):
	logout(request)
	messages.success(request, "Logged out successfully!")
	return redirect("accounts:login")

task/views.py
# Django Imports
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Own Imports
from task.models import Todo
from task.forms import TodoForm
from task.selectors import get_note


@login_required(login_url="/auth/login/")
def home(request: HttpRequest) -> HttpResponse:
    todo_list = Todo.objects.only("title", "description").filter(
        user=request.user
    )

    paginator = Paginator(todo_list, 2)
    page = request.GET.get("page", 1)

    try:
        todos = paginator.page(page)
    except PageNotAnInteger:
        todos = paginator.page(1)
    except EmptyPage:
        todos = paginator.page(paginator.num_pages)

    return render(
        request,
        "task/list-tasks.html",
        {"todos": todos, "page": page},
    )


@login_required(login_url="/auth/login/")
def create_todo(request: HttpRequest):
    form = TodoForm()

    if request.method == "POST":
        form = TodoForm(request.POST)
        if form.is_valid():
            todo = form.save(commit=False)
            todo.user = request.user
            todo.save()

            messages.success(request, "Successfully created todo!")
            return redirect("task:home")

        messages.error(request, "Creation of todo failed!")
        return HttpResponseRedirect()

    return render(request, "task/create-task.html", {"form": form})


@login_required(login_url="/auth/login/")
def view_note(request: HttpRequest, pk: int) -> HttpResponse:
    note = get_note(pk, request.user)
    return render(request, "task/view-note.html", {"note": note, "pk": pk})


@login_required(login_url="/auth/login/")
def update_note(request: HttpRequest, pk: int):
    note = get_note(pk, request.user)
    form = TodoForm(instance=note)

    if request.method == "POST":
        form = TodoForm(request.POST, instance=note)
        if form.is_valid():
            form.save()

            messages.success(request, "Successfully updated todo!")
            return redirect("task:home")

        messages.error(request, "Update of todo failed!")
        return HttpResponseRedirect("task:update_note")
    return render(request, "task/update-note.html", {"form": form})


@login_required(login_url="/auth/login/")
def delete_note(request: HttpRequest, pk: int):
    todo = get_note(pk, request.user)
    todo.delete()

    messages.success(request, "Successfully deleted todo!")
    return HttpResponseRedirect("/todos/")

templates/accounts/auth-base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Create free notes. Responsive.">
    <meta name="keywords" content="notes, crud, django">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>Todoist</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <div class="container">
                    <a href="{% url 'task:home' %}" class="navbar-brand" style="font-size: 25px;">Todoist</a>
                </div>
            </div>
        </nav>
    </header>

	{% block content %}
	{% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>

</html>

templates/accounts/login.html
{% extends 'accounts/auth-base.html' %}

{% block content %}
<div class="container"><br><br><br>
    <form method="POST">
    {% csrf_token %}
    <div class="row">
		{% if messages %}
		<ul class="messages">
			{% for message in messages %}
			<li{% if message.tags %} class="alert alert-success"{% endif %}>{{ message }}</li>
			{% endfor %}
		</ul>
		{% endif %}

		<div class="col-12 mb-4">
			<label for="username">Enter Username:</label>
			{{ form.username }}
		</div>
		<div class="col-12">
			<label for="password">Enter Password:</label>
			{{ form.password }}
		</div>
		</div><br><br>
		<div class="col-12">
			<button type="submit" class="btn btn-outline-light bg-success w-100">Login</button>
		</div>
    </div>
    </form>
</div>
{% endblock %}

templates/accounts/sign-up.html
{% extends 'accounts/auth-base.html' %}

{% block content %}
<div class="container"><br><br><br>
    <form method="POST">
		{% csrf_token %}
		<div class="row">
			{% if messages %}
			<ul class="messages">
				{% for message in messages %}
				<li{% if message.tags %} class="alert alert-warning"{% endif %}>{{ message }}</li>
				{% endfor %}
			</ul>
			{% endif %}

			<div class="col-12 mb-4">
				<label for="username">Enter Username:</label>
				{{ form.username }}
			</div>
			<div class="col-12">
				<label for="password">Enter Password:</label>
				{{ form.password }}
			</div>
			</div><br><br>
			<div class="col-12">
				<button type="submit" class="btn btn-outline-light bg-success w-100">Register</button>
			</div>
		</div>
    </form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Create free notes. Responsive.">
    <meta name="keywords" content="notes, crud, django">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>Todoist</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <div class="container">
                    <a href="{% url 'task:home' %}" class="navbar-brand" style="font-size: 25px;">Todoist</a>
                    <a href="{% url 'accounts:logout' %}" class="navbar-brand" style="font-size: 15px;">Logout</a>
                </div>
            </div>
        </nav>
    </header>

    {% if not request.user.is_authenticated %}
        <div class="text-center mt-5">
            <h2 class="text-bold pb-3">You are not logged in!</h2>
            <a href="{% url 'accounts:register' %}" class="btn btn-secondary">Sign Up</a> | <a href="{% url 'accounts:login' %}" class="btn btn-primary">Login</a>
        </div>
    {% else %}
        {% block content %}
        {% endblock %}
    {% endif %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>

</html>

templates/task/create-task.html
{% extends 'base.html' %}

{% block content %}
<div class="container"><br><br><br>
    <form method="POST">
    {% csrf_token %}
    <div class="row">
        {% if messages %}
		<ul class="messages">
			{% for message in messages %}
			<li{% if message.tags %} class="alert alert-error"{% endif %}>{{ message }}</li>
			{% endfor %}
		</ul>
		{% endif %}

        <div class="col-12 mb-4">
			<label for="username">Title of Note:</label>
            {{ form.title }}
        </div>
        
        <div class="col-12">
			<label for="username">Description of Note:</label>
            {{ form.description }}
        </div>
        </div><br><br>

        <button type="submit" class="btn btn-outline-light bg-primary">Create Note</button>
    </div>
    </form>
</div>
{% endblock %}

templates/task/list-tasks.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <br><br><br>
    <div class="container">
        <main class="role">
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="alert alert-success"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <hr>

            {% for todo in todos %}
            <article class="media content-section">
                <div class="media-body">
                    <div class="article-metadata">
                        <a href="{% url 'task:view_note' todo.id %}" style="text-decoration-color: #6c757d!important;">
                            <h2 class="text-secondary text-underline-secondary">{{ todo.title }}</h2>
                        </a>
                        {% if note.completed %} <span class="badge badge-success">completed</span> {% else %} <span class="badge badge-secondary">not completed</span> {% endif %}
                    </div>
                </div>
            </article>
            <hr>
            {% endfor %}
            <br>

            <!-- Pagination -->
            {% if todos.has_other_pages %}
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    {% if todos.has_previous %}
                        <li class="page-item"><a href="?page={{ todos.previous_page_number }}">&laquo;</a></li>
                        {% else %}
                        <li class="page-item disabled"><span>&laquo;</span></li>
                    {% endif %}

                    {% for i in todos.paginator.page_range %}
                        {% if todos.number == i %}
                            <li class="active page-item">
                                <span>{{ i }}<span class="sr-only">(current)</span></span>
                            </li>
                        {% else %}
                            <li><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if todos.has_next %}
                        <li class="page-item">
                            <a href="?page={{ todos.next_page_number }}" class="page-link">&raquo;</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <span>&raquo;</span>
                        </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
              <!-- End of Pagination -->

        </main>
    </div>
    <br>

    <div class="container">
        <a href="{% url 'task:create_note' %}" class="btn btn-dark btn-fill float-right" style="color: white;">Add</a>
    </div>

</div>
{% endblock %}

templates/task/update-note.html
{% extends 'base.html' %}


{% block content %}
<div class="container"><br><br><br>
    <form method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col-12 mb-4">
			<label for="username">Title of Note:</label>
            {{ form.title }}
        </div>
        
        <div class="col-12 mb-4">
			<label for="username">Description of Note:</label>
            {{ form.description }}
        </div>

        <div class="col-12">
            <label for="completed">
            Completed: 
            {{ form.completed }}
            </label>
        </div>
        </div><br><br>

        <button type="submit" class="btn btn-outline-light bg-warning">Update Note</button>
    
    </div>
    </form>
</div>
{% endblock %}

templates/task/view-note.html
{% extends 'base.html' %}


{% block content %}
<div class="container"><br><br><br>
    <div class="container">
        <main class="role">
            <h3 class="cursive">
                {{ note.title }} - {% if note.completed %} <span class="badge badge-success">completed</span> {% else %} <span class="badge badge-secondary">not completed</span> {% endif %}
            </h3>
            <p class="text-muted">
                {{ note.description }}
            </p>
        </main>
    </div>
    <hr>

    <div class="container inline-group">
        <a href="{% url 'task:delete_note' pk %}" class="btn btn-danger float-right" style="margin: 0px 3px;">Delete</a>
        <a href="{% url 'task:edit_note' pk %}" class="btn btn-warning float-right" style="color: white;">Edit</a>
    </div>
</div>
{% endblock %}